name: "Setup Cpp"
description: "Install all the tools required for building and testing C++/C projects."
author: "Amin Yahyaabadi"

inputs:
  compiler:
    description: "The compiler and its version."
    required: false
  architecture:
    description: "The CPU architecture"
    required: false
  cmake:
    description: "The cmake version to install."
    default: '3.20.2'
    required: false
  ninja:
    description: "The ninja version to install."
    required: false

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "award"
  color: "blue"
