name: "Setup Cpp"
description: "Install all the tools required for building and testing C++/C projects."
author: "Amin Yahyaabadi"

inputs:
  architecture:
    description: "The CPU architecture"
    required: false
  llvm:
    description: "The llvm version to install"
    required: false
  msvc:
    description: "The msvc version to install"
    required: false
  cmake:
    description: "The cmake version to install."
    default: "3.20.2"
    required: false
  ninja:
    description: "The ninja version to install."
    default: "1.10.2"
    required: false
  conan:
    description: "The conan version to install."
    required: false
  meson:
    description: "The meson version to install."
    required: false
  gcovr:
    description: "The gcovr version to install."
    required: false
  python:
    description: "The pyhon version to install."
    default: "3.x"
    required: false
  ccache:
    description: "The ccache version to install."
    required: false
  doxygen:
    description: "The doxygen version to install."
    required: false
  cppcheck:
    description: "The cppcheck version to install."
    required: false
  opencppcoverage:
    description: "The opencppcoverage version to install."
    required: false

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "award"
  color: "blue"
